pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: automatic merge dependency updates
    conditions:
      - status-success=build
      - author~=(pyup-bot|dependabot)
      - -files~=^(!?.github/workflows/)
    actions:
      merge:
        method: rebase
      delete_head_branch: {}
