name: .NET Core

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Make nuget package
      run: dotnet pack --output nupkgs
    - name: Push to Nuget
      run: nuget push nupkgs/*.nupkg -k ${{ secrets.NUGET }}
  
